controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Exemple de route à créer  *

# home-list: *
# path: /list  <- chemin de l'url*
# controller: (mettre chemin) *

home-list:
  path: /article
  controller: App\Controller\ArticleController ::index
